// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_MAIN_H
#define UI_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Main
extern void ui_Main_screen_init(void);
extern void ui_Main_screen_destroy(void);
extern lv_obj_t * ui_Main;
extern void ui_event_btnTalk(lv_event_t * e);
extern lv_obj_t * ui_btnTalk;
extern void ui_event_btnSetting(lv_event_t * e);
extern lv_obj_t * ui_btnSetting;
extern lv_obj_t * ui_tachat;
// CUSTOM VARIABLES
extern lv_obj_t * uic_btnTalk;
extern lv_obj_t * uic_btnSetting;
extern lv_obj_t * uic_tachat;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

