// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_tachat;
lv_obj_t * uic_btnSetting;
lv_obj_t * uic_btnTalk;
lv_obj_t * ui_Main = NULL;
lv_obj_t * ui_btnTalk = NULL;
lv_obj_t * ui_btnSetting = NULL;
lv_obj_t * ui_tachat = NULL;
// event funtions
void ui_event_btnTalk(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        chat_screen_on_record_start(e);
    }
    if(event_code == LV_EVENT_RELEASED) {
        chat_screen_on_record_stop(e);
    }
}

void ui_event_btnSetting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_Settings_screen_init);
    }
}

// build funtions

void ui_Main_screen_init(void)
{
    ui_Main = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnTalk = lv_button_create(ui_Main);
    lv_obj_set_width(ui_btnTalk, 50);
    lv_obj_set_height(ui_btnTalk, 50);
    lv_obj_set_x(ui_btnTalk, 197);
    lv_obj_set_y(ui_btnTalk, 125);
    lv_obj_set_align(ui_btnTalk, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnTalk, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnTalk, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnSetting = lv_button_create(ui_Main);
    lv_obj_set_width(ui_btnSetting, 66);
    lv_obj_set_height(ui_btnSetting, 50);
    lv_obj_set_x(ui_btnSetting, -204);
    lv_obj_set_y(ui_btnSetting, 127);
    lv_obj_set_align(ui_btnSetting, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnSetting, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnSetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnSetting, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnSetting, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnSetting, &ui_img_config_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tachat = lv_textarea_create(ui_Main);
    lv_obj_set_width(ui_tachat, 450);
    lv_obj_set_height(ui_tachat, 240);
    lv_obj_set_x(ui_tachat, 0);
    lv_obj_set_y(ui_tachat, -30);
    lv_obj_set_align(ui_tachat, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_tachat, "Placeholder...");
    lv_obj_set_style_text_font(ui_tachat, &ui_font_lvfontnotoserif14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnTalk, ui_event_btnTalk, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnSetting, ui_event_btnSetting, LV_EVENT_ALL, NULL);
    uic_btnTalk = ui_btnTalk;
    uic_btnSetting = ui_btnSetting;
    uic_tachat = ui_tachat;

}

void ui_Main_screen_destroy(void)
{
    if(ui_Main) lv_obj_del(ui_Main);

    // NULL screen variables
    ui_Main = NULL;
    uic_btnTalk = NULL;
    ui_btnTalk = NULL;
    uic_btnSetting = NULL;
    ui_btnSetting = NULL;
    uic_tachat = NULL;
    ui_tachat = NULL;

}
