// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_SETTINGS_H
#define UI_SETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Settings
extern void ui_Settings_screen_init(void);
extern void ui_Settings_screen_destroy(void);
extern lv_obj_t * ui_Settings;
extern void ui_event_btnBack(lv_event_t * e);
extern lv_obj_t * ui_btnBack;
extern void ui_event_btnSave(lv_event_t * e);
extern lv_obj_t * ui_btnSave;
extern lv_obj_t * ui_tfssid;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_tfpassword;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_tfgeminikey;
extern lv_obj_t * ui_lbtoast;
// CUSTOM VARIABLES
extern lv_obj_t * uic_btnBack;
extern lv_obj_t * uic_btnSave;
extern lv_obj_t * uic_tfssid;
extern lv_obj_t * uic_tfpassword;
extern lv_obj_t * uic_tfgeminikey;
extern lv_obj_t * uic_lbtoast;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

