// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_lbtoast;
lv_obj_t * uic_tfgeminikey;
lv_obj_t * uic_tfpassword;
lv_obj_t * uic_tfssid;
lv_obj_t * uic_btnSave;
lv_obj_t * uic_btnBack;
lv_obj_t * ui_Settings = NULL;
lv_obj_t * ui_btnBack = NULL;
lv_obj_t * ui_btnSave = NULL;
lv_obj_t * ui_tfssid = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_tfpassword = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_tfgeminikey = NULL;
lv_obj_t * ui_lbtoast = NULL;
// event funtions
void ui_event_btnBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_Main_screen_init);
    }
}

void ui_event_btnSave(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        config_screen_on_save(e);
    }
}

// build funtions

void ui_Settings_screen_init(void)
{
    ui_Settings = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnBack = lv_button_create(ui_Settings);
    lv_obj_set_width(ui_btnBack, 67);
    lv_obj_set_height(ui_btnBack, 50);
    lv_obj_set_x(ui_btnBack, 5);
    lv_obj_set_y(ui_btnBack, 258);
    lv_obj_add_flag(ui_btnBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnBack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnBack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnBack, &ui_img_back_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSave = lv_button_create(ui_Settings);
    lv_obj_set_width(ui_btnSave, 59);
    lv_obj_set_height(ui_btnSave, 50);
    lv_obj_set_x(ui_btnSave, 203);
    lv_obj_set_y(ui_btnSave, 126);
    lv_obj_set_align(ui_btnSave, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnSave, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnSave, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnSave, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnSave, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnSave, &ui_img_save_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tfssid = lv_textarea_create(ui_Settings);
    lv_obj_set_width(ui_tfssid, 450);
    lv_obj_set_height(ui_tfssid, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_tfssid, 0);
    lv_obj_set_y(ui_tfssid, -76);
    lv_obj_set_align(ui_tfssid, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_tfssid, "Meduverse");
    lv_textarea_set_placeholder_text(ui_tfssid, "Placeholder...");
    lv_textarea_set_one_line(ui_tfssid, true);

    ui_Label1 = lv_label_create(ui_Settings);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 15);
    lv_obj_set_y(ui_Label1, 11);
    lv_label_set_text(ui_Label1, "Settings");

    ui_Label2 = lv_label_create(ui_Settings);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 15);
    lv_obj_set_y(ui_Label2, 40);
    lv_label_set_text(ui_Label2, "SSID");

    ui_tfpassword = lv_textarea_create(ui_Settings);
    lv_obj_set_width(ui_tfpassword, 450);
    lv_obj_set_height(ui_tfpassword, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_tfpassword, 0);
    lv_obj_set_y(ui_tfpassword, -3);
    lv_obj_set_align(ui_tfpassword, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_tfpassword, "fptnextedu");
    lv_textarea_set_placeholder_text(ui_tfpassword, "Placeholder...");
    lv_textarea_set_one_line(ui_tfpassword, true);
    lv_textarea_set_password_mode(ui_tfpassword, true);

    ui_Label3 = lv_label_create(ui_Settings);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 15);
    lv_obj_set_y(ui_Label3, 113);
    lv_label_set_text(ui_Label3, "Password");

    ui_Label4 = lv_label_create(ui_Settings);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 15);
    lv_obj_set_y(ui_Label4, 184);
    lv_label_set_text(ui_Label4, "Gemini API Key");

    ui_tfgeminikey = lv_textarea_create(ui_Settings);
    lv_obj_set_width(ui_tfgeminikey, 450);
    lv_obj_set_height(ui_tfgeminikey, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_tfgeminikey, 0);
    lv_obj_set_y(ui_tfgeminikey, 69);
    lv_obj_set_align(ui_tfgeminikey, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_tfgeminikey, "AIzaSyDixf_p6bvDU9UmHFmf-8gTlI00B4aTjDE");
    lv_textarea_set_placeholder_text(ui_tfgeminikey, "Placeholder...");
    lv_textarea_set_one_line(ui_tfgeminikey, true);
    lv_textarea_set_password_mode(ui_tfgeminikey, true);

    ui_lbtoast = lv_label_create(ui_Settings);
    lv_obj_set_width(ui_lbtoast, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbtoast, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbtoast, 88);
    lv_obj_set_y(ui_lbtoast, 7);
    lv_label_set_text(ui_lbtoast, "...");
    lv_obj_set_style_text_font(ui_lbtoast, &ui_font_lvfontnotoserif14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnBack, ui_event_btnBack, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnSave, ui_event_btnSave, LV_EVENT_ALL, NULL);
    uic_btnBack = ui_btnBack;
    uic_btnSave = ui_btnSave;
    uic_tfssid = ui_tfssid;
    uic_tfpassword = ui_tfpassword;
    uic_tfgeminikey = ui_tfgeminikey;
    uic_lbtoast = ui_lbtoast;

}

void ui_Settings_screen_destroy(void)
{
    if(ui_Settings) lv_obj_del(ui_Settings);

    // NULL screen variables
    ui_Settings = NULL;
    uic_btnBack = NULL;
    ui_btnBack = NULL;
    uic_btnSave = NULL;
    ui_btnSave = NULL;
    uic_tfssid = NULL;
    ui_tfssid = NULL;
    ui_Label1 = NULL;
    ui_Label2 = NULL;
    uic_tfpassword = NULL;
    ui_tfpassword = NULL;
    ui_Label3 = NULL;
    ui_Label4 = NULL;
    uic_tfgeminikey = NULL;
    ui_tfgeminikey = NULL;
    uic_lbtoast = NULL;
    ui_lbtoast = NULL;

}
