// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdbool.h>

// Event handlers
void chat_screen_on_record_start(lv_event_t * e);
void chat_screen_on_record_stop(lv_event_t * e);
void config_screen_on_save(lv_event_t * e);

// Chat helpers
void chat_screen_append_user(const char *txt);
void chat_screen_append_bot(const char *txt);

// Core text processing
void handle_user_text(const char *text);

// UI manager functions
void ui_manager_set_recording_indicator(bool recording);
void ui_manager_switch_to_settings_screen(void);
void ui_manager_switch_to_chat_screen(void);
void ui_manager_show_toast(const char *msg);
bool ui_manager_is_voice_recording(void);

// Task declaration - implemented in ui_events.c
void voice_recording_task(void *parameter);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif